apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc-2
  namespace: yosefgu-dev   
spec:
  selector:
    app: mongodb-server-2  
  ports:
    - protocol: TCP
      port: 27017          
      targetPort: 27017    
  type: ClusterIP         
